// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAkzcPX03dA2-n-CMGyxvCZykTYen7Hko',
    appId: '1:181069547155:web:10b3b970ca64eedd13ef66',
    messagingSenderId: '181069547155',
    projectId: 'todoapp-abd9d',
    authDomain: 'todoapp-abd9d.firebaseapp.com',
    storageBucket: 'todoapp-abd9d.firebasestorage.app',
    measurementId: 'G-H84GM10W2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfYLQwiIkM8n6IEN7tC4vki46dhpqmmLw',
    appId: '1:181069547155:android:81311f094d433bc513ef66',
    messagingSenderId: '181069547155',
    projectId: 'todoapp-abd9d',
    storageBucket: 'todoapp-abd9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzGeEBx56m2ByNCmq3Gv9-y2FLtPjnNpg',
    appId: '1:181069547155:ios:1a4d62b8a6496a1413ef66',
    messagingSenderId: '181069547155',
    projectId: 'todoapp-abd9d',
    storageBucket: 'todoapp-abd9d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzGeEBx56m2ByNCmq3Gv9-y2FLtPjnNpg',
    appId: '1:181069547155:ios:1a4d62b8a6496a1413ef66',
    messagingSenderId: '181069547155',
    projectId: 'todoapp-abd9d',
    storageBucket: 'todoapp-abd9d.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAkzcPX03dA2-n-CMGyxvCZykTYen7Hko',
    appId: '1:181069547155:web:2745b809a56a1ccb13ef66',
    messagingSenderId: '181069547155',
    projectId: 'todoapp-abd9d',
    authDomain: 'todoapp-abd9d.firebaseapp.com',
    storageBucket: 'todoapp-abd9d.firebasestorage.app',
    measurementId: 'G-VD8YZYXYSL',
  );
}
